server:
    port: 5000 # Gateway listens on port 5000

spring:
    cloud:
        gateway:
            server:
                webflux:
                    routes:
                        - id: auth-module-route
                          uri: http://auth-module:8001
                          predicates:
                              - Path=/auth/**
                          filters:
                              - StripPrefix=1

                        # Route for /api/v1/user/** to user-module
                        - id: user-module-route
                          uri: http://user-module:8000
                          predicates:
                              - Path=/api/v1/user/**
                          filters:
                              - StripPrefix=3
                              - Jwt

                        # Route for /api/v1/quiz/** to quiz-module
                        - id: quiz-module-route
                          uri: http://quiz-module:8002
                          predicates:
                              - Path=/api/v1/quiz/**
                          filters:
                              - StripPrefix=3
                              - Jwt

                        # Route for /api/v1/question/** to question-module# Route for /api/docs/patients to patient-service /v3/api-docs
                        - id: api-docs-user-route
                          uri: http://user-module:8000
                          predicates:
                            - Path=/api-docs/user
                          filters:
                            - RewritePath=/api-docs/user, /v3/api-docs

                        - id: api-docs-auth-route
                          uri: http://auth-module:8001
                          predicates:
                            - Path=/api-docs/auth
                          filters:
                            - RewritePath=/api-docs/auth, /v3/api-docs

                        - id: api-docs-quiz-route
                          uri: http://quiz-module:8002
                          predicates:
                            - Path=/api-docs/quiz
                          filters:
                            - RewritePath=/api-docs/quiz, /v3/api-docs