spring.application.name=user-module

server.port=8000
logging.level.root=info
logging.level.org.hibernate.SQL=debug
# Database configuration
#spring.datasource.url=jdbc:postgresql://localhost:5432/ielts_db
#spring.datasource.username=kant2510
#spring.datasource.password=TYUhnNjik,lp
#spring.jpa.hibernate.ddl-auto=validate
#spring.sql.init.mode=never